# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
