# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160924_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(through='core.Attendance', to='core.Person'),
        ),
        migrations.AddField(
            model_name='movement',
            name='votes',
            field=models.ManyToManyField(through='core.Vote', to='core.Person'),
        ),
    ]
